language: ruby

sudo: required

services:
- docker

before_install:
- date
- docker login --username=${DOCKER_USER} --password=${DOCKER_PASS}

script: make build

deploy:
  provider: script
  script: make build publish
  skip_cleanup: true
  on:
    tags: true
  repo: riggerthegeek/get-iplayer
